import type { Post, Tag, UserProfile } from "./types";

export const USERS: UserProfile[] = [
  {
    id: "1",
    name: "Amara Osei",
    username: "amara_o",
    university: "Howard University",
    level: "Junior",
    relationshipStatus: "Single",
    gender: "Female",
    avatar: "AO",
    badge: "blue",
    isActive: true,
    followers: 1240,
    bio: "Pre-med • Campus ambassador • Coffee addict ☕",
  },
  {
    id: "2",
    name: "Jordan Blake",
    username: "j_blake",
    university: "MIT",
    level: "Senior",
    relationshipStatus: "Taken",
    gender: "Male",
    avatar: "JB",
    badge: "white",
    isActive: false,
    followers: 892,
    bio: "CS + Math double major. Building cool stuff.",
  },
  {
    id: "3",
    name: "Zara Mensah",
    username: "zara.m",
    university: "UCLA",
    level: "Freshman",
    relationshipStatus: "Single",
    gender: "Female",
    avatar: "ZM",
    badge: "none",
    isActive: true,
    followers: 345,
    bio: "Film studies 🎬 First year, figuring it out.",
  },
  {
    id: "4",
    name: "Kwame Asante",
    username: "kwame_a",
    university: "Stanford",
    level: "Graduate",
    relationshipStatus: "Single",
    gender: "Male",
    avatar: "KA",
    badge: "blue",
    isActive: true,
    followers: 3100,
    bio: "PhD candidate in Electrical Engineering. Researcher.",
  },
  {
    id: "5",
    name: "Riley Chen",
    username: "riley.chen",
    university: "NYU",
    level: "Sophomore",
    relationshipStatus: "It's Complicated",
    gender: "Non-binary",
    avatar: "RC",
    badge: "white",
    isActive: false,
    followers: 670,
    bio: "Art history + Music production. NYC native 🗽",
  },
  {
    id: "6",
    name: "Destiny Williams",
    username: "destinyW",
    university: "Harvard",
    level: "Senior",
    relationshipStatus: "Single",
    gender: "Female",
    avatar: "DW",
    badge: "blue",
    isActive: true,
    followers: 4800,
    bio: "Premed • HBCU proud • Aspiring surgeon 🩺",
  },
  {
    id: "7",
    name: "Marcus Lee",
    username: "marcusl",
    university: "Howard University",
    level: "Junior",
    relationshipStatus: "Taken",
    gender: "Male",
    avatar: "ML",
    badge: "none",
    isActive: true,
    followers: 520,
    bio: "Political science major. Debate team captain.",
  },
  {
    id: "8",
    name: "Nia Jackson",
    username: "nia_j",
    university: "UCLA",
    level: "Graduate",
    relationshipStatus: "Single",
    gender: "Female",
    avatar: "NJ",
    badge: "blue",
    isActive: false,
    followers: 2300,
    bio: "MBA candidate. Entrepreneur. Startup life 🚀",
  },
];

export const POSTS: Post[] = [
  {
    id: "p1",
    user: USERS[0],
    content:
      "Just aced my biochemistry midterm! The campus study rooms were packed but worth it 🙌 Anyone else feeling the midterm grind? #MidtermSzn #PreMed",
    tags: ["MidtermSzn", "PreMed"],
    likes: 284,
    comments: 41,
    reposts: 18,
    time: "2h",
  },
  {
    id: "p2",
    user: USERS[3],
    content:
      "New research paper dropped! Our lab just published on neural signal processing. So grateful for this team 🔬 #Research #GradLife",
    tags: ["Research", "GradLife"],
    likes: 612,
    comments: 87,
    reposts: 134,
    time: "4h",
    image: "lab",
  },
  {
    id: "p3",
    user: USERS[5],
    content:
      "Campus vibes are immaculate today ✨ Fall semester is giving everything. Who's at the quad right now? #CampusLife #HarvardMoments",
    tags: ["CampusLife", "HarvardMoments"],
    likes: 1203,
    comments: 96,
    reposts: 45,
    time: "1h",
  },
  {
    id: "p4",
    user: USERS[6],
    content:
      "Debate practice was intense tonight. We're prepping for nationals and the pressure is real. Shoutout to the whole team 💪 #Debate #CampusLife",
    tags: ["Debate", "CampusLife"],
    likes: 198,
    comments: 27,
    reposts: 12,
    time: "6h",
  },
  {
    id: "p5",
    user: USERS[4],
    content:
      "NYC in the fall hits different when you're running on 4 hours of sleep and a deadline 😂 The art history paper will NOT write itself #NYU #StudentLife",
    tags: ["NYU", "StudentLife"],
    likes: 445,
    comments: 63,
    reposts: 29,
    time: "3h",
  },
];

export const TAGS: Tag[] = [
  { id: "t1", name: "CampusLife", count: 8420 },
  { id: "t2", name: "MidtermSzn", count: 5130 },
  { id: "t3", name: "StudyGroup", count: 3870 },
  { id: "t4", name: "GradLife", count: 2950 },
  { id: "t5", name: "PreMed", count: 2310 },
  { id: "t6", name: "Research", count: 1890 },
  { id: "t7", name: "StudentLife", count: 1640 },
  { id: "t8", name: "HBCU", count: 1220 },
];

export const AVATAR_COLORS: Record<string, string> = {
  AO: "bg-violet-500",
  JB: "bg-sky-600",
  ZM: "bg-pink-500",
  KA: "bg-emerald-600",
  RC: "bg-amber-500",
  DW: "bg-rose-500",
  ML: "bg-indigo-600",
  NJ: "bg-teal-600",
};
